### ISSUE TITLE
Bang tambahin otakudesu detail

### ISSUE THREAD

**Issue by RyHarJr** [xct007/frieren-scraper#1]
otakudesu detail

komiku juga :)

**Comment by xct007** [comment]
link website komiku nya mana cuk

> otakudesu detail
> 
> komiku juga :)

**Comment by Yuri-Neko** [comment]
> link website komiku nya mana cuk
> 
> > otakudesu detail
> > komiku juga :)

https://komiku.id/ tuh bang
