### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by IzkGrim** [xct007/frieren-scraper#10]
diffusionnya eror bang..ku cek di console 401 mulu hasilnya

**Comment by xct007** [comment]
> diffusionnya eror bang..ku cek di console 401 mulu hasilnya

error dimana

**Comment by IzkGrim** [comment]
gak tau bang, ku cek di log 401 :'/
gini perintahku
const { diffusion } = require('@xct007/frieren-scraper')

// stable diffusion.
const prompt = "1girl, blush, looking to viewer, warm smile,";
const seed = 123456789;
diffusion.stable(prompt, seed).then(async (anu) => {
console.log(anu);
})

fitur lain kek downloader work kalo stablenya nggak

**Comment by xct007** [comment]
API nya yang error, ini lagi ku fix.

**Comment by xct007** [comment]
> gak tau bang, ku cek di log 401 :'/ gini perintahku const { diffusion } = require('@xct007/frieren-scraper')
> 
> // stable diffusion. const prompt = "1girl, blush, looking to viewer, warm smile,"; const seed = 123456789; diffusion.stable(prompt, seed).then(async (anu) => { console.log(anu); })
> 
> fitur lain kek downloader work kalo stablenya nggak

Stable diffusion sudah fix 👌
