### ISSUE TITLE
request Nhentai search, detail

### ISSUE THREAD

**Issue by Xvannn07** [xct007/frieren-scraper#16]
Base https://nhentai.to/

**Comment by xct007** [comment]
okay 👌

**Comment by xct007** [comment]
> Base https://nhentai.to/

you can test nhentai search and detail from repo now.

```js
import { nhentai } from "@xct007/frieren-scraper"

await nhentai.search("mom")
await nhentai.detail(12344)
```

make sure you install repo version 👍

**Comment by Xvannn07** [comment]
> > Base https://nhentai.to/
> 
> you can test nhentai search and detail from repo now.
> 
> ```js
> import { nhentai } from "@xct007/frieren-scraper"
> 
> await nhentai.search("mom")
> await nhentai.detail(12344)
> ```
> 
> make sure you install repo version 👍

Nice

**Comment by xct007** [comment]
> > > Base https://nhentai.to/
> > 
> > 
> > you can test nhentai search and detail from repo now.
> > ```js
> > import { nhentai } from "@xct007/frieren-scraper"
> > 
> > await nhentai.search("mom")
> > await nhentai.detail(12344)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > make sure you install repo version 👍
> 
> Nice

👍
