### ISSUE TITLE
GW BENERAN MINTA REQUEST TOLONG BACA DAPID

### ISSUE THREAD

**Issue by Yuri-Neko** [xct007/frieren-scraper#4]
bikin scrap otakudesu batch
jadi ntar result nya link batch dri anime yang uda completed 
link gdrive dll

**Comment by xct007** [comment]
udah meki

**Comment by Yuri-Neko** [comment]
> udah meki

🐤tambahin cara pakenya di README.md

**Comment by xct007** [comment]
> > udah meki
> 
> 🐤tambahin cara pakenya di README.md

belum selesai su, masa iya fitur nya cuman 2

**Comment by Yuri-Neko** [comment]
> > > udah meki
> > 
> > 
> > 🐤tambahin cara pakenya di README.md
> 
> belum selesai su, masa iya fitur nya cuman 2

hmm 🐤wakatta... hmm masih open request?
