### ISSUE TITLE
Error bang benerin

### ISSUE THREAD

**Issue by kenshinaru** [xct007/frieren-scraper#50]
Gabisa search error gini :  {
  "error": true,
  "message": "Error: failed to get search data from https://komiku.id"
}

Terur error gabisa ambil gambar comic : {
  "error": true,
  "message": "TypeError: Cannot read property 'replace' of undefined"
}

**Comment by xct007** [comment]
[fix](https://github.com/xct007/frieren-scraper/commit/8453b9b914dff194b4b0d282f449385b4ac0e4e3)
