### ISSUE TITLE
Ubah Web

### ISSUE THREAD

**Issue by kenshinaru** [xct007/frieren-scraper#51]
Ganti bang jangan komiku webnya, bagusan shinigami.id

**Comment by xct007** [comment]
Palakau

**Comment by kenshinaru** [comment]
Download anime lah bang, tapi kalo bisa yang send videonya, per eps aja palingan dibawah 100mb an, masih bisa ngangkat, jangan url download

**Comment by xct007** [comment]
> Download anime lah bang, tapi kalo bisa yang send videonya, per eps aja palingan dibawah 100mb an, masih bisa ngangkat, jangan url download

silakan check [APIGratis](https://apigratis.site/developers)
