### ISSUE TITLE
npm error git dep preparation failed

### ISSUE THREAD

**Issue by Ftwrr** [xct007/frieren-scraper#52]
npm error code 2
npm error git dep preparation failed
npm error command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/ftwr/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm error > @xct007/frieren-scraper@0.0.2 prepare
npm error > npm run build:all
npm error
npm error
npm error > @xct007/frieren-scraper@0.0.2 build:all
npm error > npm run clean && npm run build:esm && npm run build:cjs && npm run build:types && npm run fix && node scripts/write-package.js
npm error
npm error
npm error > @xct007/frieren-scraper@0.0.2 clean
npm error > rimraf ./dist
npm error
npm error
npm error > @xct007/frieren-scraper@0.0.2 build:esm
npm error > tsc -p tsconfig.esm.json
npm error
npm error node_modules/cheerio/dist/commonjs/index.d.ts(7,1): error TS1383: Only named exports may use 'export type'.
npm error node_modules/cheerio/dist/commonjs/slim.d.ts(9,1): error TS1383: Only named exports may use 'export type'.
npm error npm warn using --force Recommended protections disabled.
npm error npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm error npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm error npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm error npm warn using --force Recommended protections disabled.
npm error npm warn using --force Recommended protections disabled.
npm error npm warn using --force Recommended protections disabled.
npm error npm error code 2
npm error npm error path /home/ftwr/.npm/_cacache/tmp/git-cloneRnukLc
npm error npm error command failed
npm error npm error command sh -c npm run build:all
npm error npm error A complete log of this run can be found in: /home/ftwr/.npm/_logs/2024-09-26T16_54_25_636Z-debug-0.log
npm error A complete log of this run can be found in: /home/ftwr/.npm/_logs/2024-09-26T16_54_18_862Z-debug-0.log

**Comment by Ftwrr** [comment]
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.8.3
2 info using node@v20.17.0
3 silly config load:file:/usr/lib/node_modules/npm/npmrc
4 silly config load:file:/DATA/Documents/botwaweb/.npmrc
5 silly config load:file:/root/.npmrc
6 silly config load:file:/usr/etc/npmrc
7 verbose title npm install
8 verbose argv "install"
9 verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-09-26T16_57_26_430Z-
10 verbose logfile /root/.npm/_logs/2024-09-26T16_57_26_430Z-debug-0.log
11 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
12 silly logfile done cleaning log files
13 silly idealTree buildDeps
14 silly fetch manifest @xct007/frieren-scraper@github:xct007/frieren-scraper
15 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
16 silly placeDep ROOT @xct007/frieren-scraper@0.0.2 OK for: botwaweb@0.0.1 want: github:xct007/frieren-scraper
17 silly fetch manifest axios@^1.3.4
18 silly packumentCache full:https://registry.npmjs.org/axios cache-miss
19 http fetch GET 200 https://registry.npmjs.org/axios 464ms (cache miss)
20 silly packumentCache full:https://registry.npmjs.org/axios set size:undefined disposed:false
21 silly fetch manifest cheerio@^1.0.0-rc.12
22 silly packumentCache full:https://registry.npmjs.org/cheerio cache-miss
23 http fetch GET 200 https://registry.npmjs.org/cheerio 103ms (cache miss)
24 silly packumentCache full:https://registry.npmjs.org/cheerio set size:undefined disposed:false
25 silly placeDep ROOT axios@1.7.7 OK for: @xct007/frieren-scraper@0.0.2 want: ^1.3.4
26 silly placeDep ROOT cheerio@1.0.0 OK for: @xct007/frieren-scraper@0.0.2 want: ^1.0.0-rc.12
27 silly fetch manifest form-data@^4.0.0
28 silly packumentCache full:https://registry.npmjs.org/form-data cache-miss
29 http fetch GET 200 https://registry.npmjs.org/form-data 107ms (cache miss)
30 silly packumentCache full:https://registry.npmjs.org/form-data set size:undefined disposed:false
31 silly fetch manifest follow-redirects@^1.15.6
32 silly packumentCache full:https://registry.npmjs.org/follow-redirects cache-miss
33 http fetch GET 200 https://registry.npmjs.org/follow-redirects 123ms (cache miss)
34 silly packumentCache full:https://registry.npmjs.org/follow-redirects set size:undefined disposed:false
35 silly fetch manifest cheerio-select@^2.1.0
36 silly packumentCache full:https://registry.npmjs.org/cheerio-select cache-miss
37 http fetch GET 200 https://registry.npmjs.org/cheerio-select 102ms (cache miss)
38 silly packumentCache full:https://registry.npmjs.org/cheerio-select set size:undefined disposed:false
39 silly fetch manifest encoding-sniffer@^0.2.0
40 silly packumentCache full:https://registry.npmjs.org/encoding-sniffer cache-miss
41 http fetch GET 200 https://registry.npmjs.org/encoding-sniffer 116ms (cache miss)
42 silly packumentCache full:https://registry.npmjs.org/encoding-sniffer set size:undefined disposed:false
43 silly fetch manifest htmlparser2@^9.1.0
44 silly packumentCache full:https://registry.npmjs.org/htmlparser2 cache-miss
45 http fetch GET 200 https://registry.npmjs.org/htmlparser2 114ms (cache miss)
46 silly packumentCache full:https://registry.npmjs.org/htmlparser2 set size:undefined disposed:false
47 silly fetch manifest parse5@^7.1.2
48 silly packumentCache full:https://registry.npmjs.org/parse5 cache-miss
49 http fetch GET 200 https://registry.npmjs.org/parse5 113ms (cache miss)
50 silly packumentCache full:https://registry.npmjs.org/parse5 set size:undefined disposed:false
51 silly fetch manifest parse5-htmlparser2-tree-adapter@^7.0.0
52 silly packumentCache full:https://registry.npmjs.org/parse5-htmlparser2-tree-adapter cache-miss
53 http fetch GET 200 https://registry.npmjs.org/parse5-htmlparser2-tree-adapter 109ms (cache miss)
54 silly packumentCache full:https://registry.npmjs.org/parse5-htmlparser2-tree-adapter set size:undefined disposed:false
55 silly fetch manifest parse5-parser-stream@^7.1.2
56 silly packumentCache full:https://registry.npmjs.org/parse5-parser-stream cache-miss
57 http fetch GET 200 https://registry.npmjs.org/parse5-parser-stream 119ms (cache miss)
58 silly packumentCache full:https://registry.npmjs.org/parse5-parser-stream set size:undefined disposed:false
59 silly fetch manifest whatwg-mimetype@^4.0.0
60 silly packumentCache full:https://registry.npmjs.org/whatwg-mimetype cache-miss
61 http fetch GET 200 https://registry.npmjs.org/whatwg-mimetype 114ms (cache miss)
62 silly packumentCache full:https://registry.npmjs.org/whatwg-mimetype set size:undefined disposed:false
63 silly placeDep ROOT follow-redirects@1.15.9 OK for: axios@1.7.7 want: ^1.15.6
64 silly placeDep ROOT form-data@4.0.0 OK for: axios@1.7.7 want: ^4.0.0
65 silly fetch manifest asynckit@^0.4.0
66 silly packumentCache full:https://registry.npmjs.org/asynckit cache-miss
67 http fetch GET 200 https://registry.npmjs.org/asynckit 101ms (cache miss)
68 silly packumentCache full:https://registry.npmjs.org/asynckit set size:undefined disposed:false
69 silly fetch manifest combined-stream@^1.0.8
70 silly packumentCache full:https://registry.npmjs.org/combined-stream cache-miss
71 http fetch GET 200 https://registry.npmjs.org/combined-stream 101ms (cache miss)
72 silly packumentCache full:https://registry.npmjs.org/combined-stream set size:undefined disposed:false
73 silly fetch manifest mime-types@^2.1.12
74 silly packumentCache full:https://registry.npmjs.org/mime-types cache-miss
75 http fetch GET 200 https://registry.npmjs.org/mime-types 106ms (cache miss)
76 silly packumentCache full:https://registry.npmjs.org/mime-types set size:undefined disposed:false
77 silly placeDep ROOT cheerio-select@2.1.0 OK for: cheerio@1.0.0 want: ^2.1.0
78 silly placeDep ROOT encoding-sniffer@0.2.0 OK for: cheerio@1.0.0 want: ^0.2.0
79 silly placeDep ROOT htmlparser2@9.1.0 OK for: cheerio@1.0.0 want: ^9.1.0
80 silly placeDep ROOT parse5@7.1.2 OK for: cheerio@1.0.0 want: ^7.1.2
81 silly placeDep ROOT parse5-htmlparser2-tree-adapter@7.0.0 OK for: cheerio@1.0.0 want: ^7.0.0
82 silly placeDep ROOT parse5-parser-stream@7.1.2 OK for: cheerio@1.0.0 want: ^7.1.2
83 silly placeDep ROOT whatwg-mimetype@4.0.0 OK for: cheerio@1.0.0 want: ^4.0.0
84 silly fetch manifest iconv-lite@^0.6.3
85 silly packumentCache full:https://registry.npmjs.org/iconv-lite cache-miss
86 http fetch GET 200 https://registry.npmjs.org/iconv-lite 87ms (cache miss)
87 silly packumentCache full:https://registry.npmjs.org/iconv-lite set size:undefined disposed:false
88 silly fetch manifest whatwg-encoding@^3.1.1
89 silly packumentCache full:https://registry.npmjs.org/whatwg-encoding cache-miss
90 http fetch GET 200 https://registry.npmjs.org/whatwg-encoding 101ms (cache miss)
91 silly packumentCache full:https://registry.npmjs.org/whatwg-encoding set size:undefined disposed:false
92 silly placeDep ROOT iconv-lite@0.6.3 OK for: encoding-sniffer@0.2.0 want: ^0.6.3
93 silly placeDep ROOT whatwg-encoding@3.1.1 OK for: encoding-sniffer@0.2.0 want: ^3.1.1
94 silly fetch manifest safer-buffer@>= 2.1.2 < 3.0.0
95 silly packumentCache full:https://registry.npmjs.org/safer-buffer cache-miss
96 http fetch GET 200 https://registry.npmjs.org/safer-buffer 91ms (cache miss)
97 silly packumentCache full:https://registry.npmjs.org/safer-buffer set size:undefined disposed:false
98 silly placeDep ROOT asynckit@0.4.0 OK for: form-data@4.0.0 want: ^0.4.0
99 silly placeDep ROOT combined-stream@1.0.8 OK for: form-data@4.0.0 want: ^1.0.8
100 silly placeDep ROOT mime-types@2.1.35 OK for: form-data@4.0.0 want: ^2.1.12
101 silly fetch manifest delayed-stream@~1.0.0
102 silly packumentCache full:https://registry.npmjs.org/delayed-stream cache-miss
103 http fetch GET 200 https://registry.npmjs.org/delayed-stream 100ms (cache miss)
104 silly packumentCache full:https://registry.npmjs.org/delayed-stream set size:undefined disposed:false
105 silly fetch manifest mime-db@1.52.0
106 silly packumentCache full:https://registry.npmjs.org/mime-db cache-miss
107 http fetch GET 200 https://registry.npmjs.org/mime-db 103ms (cache miss)
108 silly packumentCache full:https://registry.npmjs.org/mime-db set size:undefined disposed:false
109 silly placeDep ROOT delayed-stream@1.0.0 OK for: combined-stream@1.0.8 want: ~1.0.0
110 silly placeDep ROOT safer-buffer@2.1.2 OK for: iconv-lite@0.6.3 want: >= 2.1.2 < 3.0.0
111 silly placeDep ROOT mime-db@1.52.0 OK for: mime-types@2.1.35 want: 1.52.0
112 silly reify moves {}
113 silly audit bulk request {
113 silly audit   '@pedroslopez/moduleraid': [ '5.0.2' ],
113 silly audit   '@sec-ant/readable-stream': [ '0.4.1' ],
113 silly audit   '@tokenizer/token': [ '0.3.0' ],
113 silly audit   '@types/node': [ '22.7.2' ],
113 silly audit   '@types/yauzl': [ '2.10.3' ],
113 silly audit   acorn: [ '7.4.1' ],
113 silly audit   'acorn-node': [ '1.8.2' ],
113 silly audit   'acorn-walk': [ '7.2.0' ],
113 silly audit   'agent-base': [ '6.0.2' ],
113 silly audit   archiver: [ '5.3.2' ],
113 silly audit   'archiver-utils': [ '2.1.0', '3.0.4' ],
113 silly audit   'readable-stream': [ '2.3.8', '3.6.2' ],
113 silly audit   'safe-buffer': [ '5.1.2', '5.2.1' ],
113 silly audit   string_decoder: [ '1.1.1', '1.3.0' ],
113 silly audit   async: [ '3.2.6' ],
113 silly audit   'balanced-match': [ '1.0.2' ],
113 silly audit   'base64-js': [ '1.5.1' ],
113 silly audit   'big-integer': [ '1.6.52' ],
113 silly audit   binary: [ '0.3.0' ],
113 silly audit   bl: [ '4.1.0' ],
113 silly audit   bluebird: [ '3.4.7' ],
113 silly audit   boolbase: [ '1.0.0' ],
113 silly audit   'brace-expansion': [ '1.1.11', '2.0.1' ],
113 silly audit   buffer: [ '5.7.1' ],
113 silly audit   'buffer-crc32': [ '0.2.13' ],
113 silly audit   'buffer-indexof-polyfill': [ '1.0.2' ],
113 silly audit   buffers: [ '0.1.1' ],
113 silly audit   chainsaw: [ '0.1.0' ],
113 silly audit   chownr: [ '1.1.4' ],
113 silly audit   colorette: [ '2.0.20' ],
113 silly audit   'compress-commons': [ '4.1.2' ],
113 silly audit   'concat-map': [ '0.0.1' ],
113 silly audit   'core-util-is': [ '1.0.3' ],
113 silly audit   'crc-32': [ '1.2.2' ],
113 silly audit   'crc32-stream': [ '4.0.3' ],
113 silly audit   'cross-fetch': [ '3.1.5' ],
113 silly audit   'node-fetch': [ '2.6.7', '3.3.2', '2.7.0' ],
113 silly audit   'css-select': [ '5.1.0' ],
113 silly audit   'css-what': [ '6.1.0' ],
113 silly audit   'data-uri-to-buffer': [ '4.0.1' ],
113 silly audit   debug: [ '4.3.7', '4.3.4' ],
113 silly audit   'devtools-protocol': [ '0.0.1045489' ],
113 silly audit   'dom-serializer': [ '2.0.0' ],
113 silly audit   domelementtype: [ '2.3.0' ],
113 silly audit   domhandler: [ '5.0.3' ],
113 silly audit   domutils: [ '3.1.0' ],
113 silly audit   duplexer2: [ '0.1.4' ],
113 silly audit   'end-of-stream': [ '1.4.4' ],
113 silly audit   entities: [ '4.5.0' ],
113 silly audit   'extract-zip': [ '2.0.1' ],
113 silly audit   'get-stream': [ '5.2.0', '9.0.1' ],
113 silly audit   'fd-slicer': [ '1.1.0' ],
113 silly audit   'fetch-blob': [ '3.2.0' ],
113 silly audit   'file-type': [ '19.5.0' ],
113 silly audit   'fluent-ffmpeg': [ '2.1.2' ],
113 silly audit   'formdata-polyfill': [ '4.0.10' ],
113 silly audit   'fs-constants': [ '1.0.0' ],
113 silly audit   'fs-extra': [ '10.1.0' ],
113 silly audit   'fs.realpath': [ '1.0.0' ],
113 silly audit   fstream: [ '1.0.12' ],
113 silly audit   rimraf: [ '2.7.1', '3.0.2' ],
113 silly audit   'genius-lyrics': [ '4.4.7' ],
113 silly audit   glob: [ '7.2.3' ],
113 silly audit   'graceful-fs': [ '4.2.11' ],
113 silly audit   he: [ '1.2.0' ],
113 silly audit   'https-proxy-agent': [ '5.0.1' ],
113 silly audit   ieee754: [ '1.2.1' ],
113 silly audit   inflight: [ '1.0.6' ],
113 silly audit   inherits: [ '2.0.4' ],
113 silly audit   'is-stream': [ '4.0.1' ],
113 silly audit   isarray: [ '1.0.0' ],
113 silly audit   isexe: [ '2.0.0' ],
113 silly audit   jsonfile: [ '6.1.0' ],
113 silly audit   lazystream: [ '1.0.1' ],
113 silly audit   listenercount: [ '1.0.1' ],
113 silly audit   lodash: [ '4.17.21' ],
113 silly audit   'lodash.defaults': [ '4.2.0' ],
113 silly audit   'lodash.difference': [ '4.5.0' ],
113 silly audit   'lodash.flatten': [ '4.4.0' ],
113 silly audit   'lodash.isplainobject': [ '4.0.6' ],
113 silly audit   'lodash.union': [ '4.6.0' ],
113 silly audit   lowdb: [ '7.0.1' ],
113 silly audit   mime: [ '3.0.0' ],
113 silly audit   minimatch: [ '3.1.2', '5.1.6' ],
113 silly audit   minimist: [ '1.2.8' ],
113 silly audit   mkdirp: [ '0.5.6' ],
113 silly audit   'mkdirp-classic': [ '0.5.3' ],
113 silly audit   ms: [ '2.1.3', '2.1.2' ],
113 silly audit   'node-cron': [ '3.0.3' ],
113 silly audit   'node-domexception': [ '1.0.0' ],
113 silly audit   'node-html-parser': [ '6.1.13' ],
113 silly audit   'node-webpmux': [ '3.1.7' ],
113 silly audit   'normalize-path': [ '3.0.0' ],
113 silly audit   'nth-check': [ '2.1.1' ],
113 silly audit   once: [ '1.4.0' ],
113 silly audit   'path-is-absolute': [ '1.0.1' ],
113 silly audit   'peek-readable': [ '5.2.0' ],
113 silly audit   pend: [ '1.2.0' ],
113 silly audit   'process-nextick-args': [ '2.0.1' ],
113 silly audit   progress: [ '2.0.3' ],
113 silly audit   'proxy-from-env': [ '1.1.0' ],
113 silly audit   pump: [ '3.0.2' ],
113 silly audit   puppeteer: [ '18.2.1' ],
113 silly audit   'puppeteer-core': [ '18.2.1' ],
113 silly audit   'qrcode-terminal': [ '0.12.0' ],
113 silly audit   'readdir-glob': [ '1.1.3' ],
113 silly audit   setimmediate: [ '1.0.5' ],
113 silly audit   steno: [ '4.0.2' ],
113 silly audit   strtok3: [ '8.1.0' ],
113 silly audit   'syntax-error': [ '1.4.0' ],
113 silly audit   'tar-fs': [ '2.1.1' ],
113 silly audit   'tar-stream': [ '2.2.0' ],
113 silly audit   through: [ '2.3.8' ],
113 silly audit   'token-types': [ '6.0.0' ],
113 silly audit   tr46: [ '0.0.3' ],
113 silly audit   traverse: [ '0.3.9' ],
113 silly audit   typescript: [ '5.6.2' ],
113 silly audit   'uint8array-extras': [ '1.4.0' ],
113 silly audit   'unbzip2-stream': [ '1.4.3' ],
113 silly audit   undici: [ '6.19.8' ],
113 silly audit   'undici-types': [ '6.19.8' ],
113 silly audit   universalify: [ '2.0.1' ],
113 silly audit   unzipper: [ '0.10.14' ],
113 silly audit   'util-deprecate': [ '1.0.2' ],
113 silly audit   uuid: [ '8.3.2' ],
113 silly audit   'web-streams-polyfill': [ '3.3.3' ],
113 silly audit   'webidl-conversions': [ '3.0.1' ],
113 silly audit   'whatsapp-web.js': [ '1.26.1-alpha.1' ],
113 silly audit   'whatwg-url': [ '5.0.0' ],
113 silly audit   which: [ '1.3.1' ],
113 silly audit   wrappy: [ '1.0.2' ],
113 silly audit   ws: [ '8.9.0' ],
113 silly audit   xtend: [ '4.0.2' ],
113 silly audit   yauzl: [ '2.10.0' ],
113 silly audit   'zip-stream': [ '4.1.1' ],
113 silly audit   '@xct007/frieren-scraper': [ '0.0.2' ],
113 silly audit   axios: [ '1.7.7' ],
113 silly audit   cheerio: [ '1.0.0' ],
113 silly audit   'follow-redirects': [ '1.15.9' ],
113 silly audit   'form-data': [ '4.0.0' ],
113 silly audit   'cheerio-select': [ '2.1.0' ],
113 silly audit   'encoding-sniffer': [ '0.2.0' ],
113 silly audit   htmlparser2: [ '9.1.0' ],
113 silly audit   parse5: [ '7.1.2' ],
113 silly audit   'parse5-htmlparser2-tree-adapter': [ '7.0.0' ],
113 silly audit   'parse5-parser-stream': [ '7.1.2' ],
113 silly audit   'whatwg-mimetype': [ '4.0.0' ],
113 silly audit   'iconv-lite': [ '0.6.3' ],
113 silly audit   'whatwg-encoding': [ '3.1.1' ],
113 silly audit   asynckit: [ '0.4.0' ],
113 silly audit   'combined-stream': [ '1.0.8' ],
113 silly audit   'mime-types': [ '2.1.35' ],
113 silly audit   'delayed-stream': [ '1.0.0' ],
113 silly audit   'safer-buffer': [ '2.1.2' ],
113 silly audit   'mime-db': [ '1.52.0' ]
113 silly audit }
114 silly tarball no local data for mime-db@https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz. Extracting by manifest.
115 silly tarball no local data for safer-buffer@https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz. Extracting by manifest.
116 silly tarball no local data for delayed-stream@https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz. Extracting by manifest.
117 silly tarball no local data for combined-stream@https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz. Extracting by manifest.
118 silly tarball no local data for asynckit@https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz. Extracting by manifest.
119 silly tarball no local data for mime-types@https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz. Extracting by manifest.
120 silly tarball no local data for whatwg-mimetype@https://registry.npmjs.org/whatwg-mimetype/-/whatwg-mimetype-4.0.0.tgz. Extracting by manifest.
121 silly tarball no local data for whatwg-encoding@https://registry.npmjs.org/whatwg-encoding/-/whatwg-encoding-3.1.1.tgz. Extracting by manifest.
122 silly tarball no local data for iconv-lite@https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz. Extracting by manifest.
123 silly tarball no local data for parse5-parser-stream@https://registry.npmjs.org/parse5-parser-stream/-/parse5-parser-stream-7.1.2.tgz. Extracting by manifest.
124 silly tarball no local data for parse5-htmlparser2-tree-adapter@https://registry.npmjs.org/parse5-htmlparser2-tree-adapter/-/parse5-htmlparser2-tree-adapter-7.0.0.tgz. Extracting by manifest.
125 silly tarball no local data for parse5@https://registry.npmjs.org/parse5/-/parse5-7.1.2.tgz. Extracting by manifest.
126 silly tarball no local data for htmlparser2@https://registry.npmjs.org/htmlparser2/-/htmlparser2-9.1.0.tgz. Extracting by manifest.
127 silly tarball no local data for encoding-sniffer@https://registry.npmjs.org/encoding-sniffer/-/encoding-sniffer-0.2.0.tgz. Extracting by manifest.
128 silly tarball no local data for cheerio-select@https://registry.npmjs.org/cheerio-select/-/cheerio-select-2.1.0.tgz. Extracting by manifest.
129 silly tarball no local data for form-data@https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz. Extracting by manifest.
130 silly tarball no local data for cheerio@https://registry.npmjs.org/cheerio/-/cheerio-1.0.0.tgz. Extracting by manifest.
131 silly tarball no local data for follow-redirects@https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.9.tgz. Extracting by manifest.
132 silly tarball no local data for axios@https://registry.npmjs.org/axios/-/axios-1.7.7.tgz. Extracting by manifest.
133 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 303ms
134 silly audit report {
134 silly audit report   ws: [
134 silly audit report     {
134 silly audit report       id: 1098392,
134 silly audit report       url: 'https://github.com/advisories/GHSA-3h5v-q93c-6h6q',
134 silly audit report       title: 'ws affected by a DoS when handling a request with many HTTP headers',
134 silly audit report       severity: 'high',
134 silly audit report       vulnerable_versions: '>=8.0.0 <8.17.1',
134 silly audit report       cwe: [Array],
134 silly audit report       cvss: [Object]
134 silly audit report     }
134 silly audit report   ]
134 silly audit report }
135 silly packumentCache corgi:https://registry.npmjs.org/ws cache-miss
136 http fetch GET 200 https://registry.npmjs.org/cheerio-select/-/cheerio-select-2.1.0.tgz 622ms (cache miss)
137 http fetch GET 200 https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz 747ms (cache miss)
138 http fetch GET 200 https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz 782ms (cache miss)
139 http fetch GET 200 https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz 774ms (cache miss)
140 http fetch GET 200 https://registry.npmjs.org/whatwg-encoding/-/whatwg-encoding-3.1.1.tgz 806ms (cache miss)
141 http fetch GET 200 https://registry.npmjs.org/parse5-parser-stream/-/parse5-parser-stream-7.1.2.tgz 806ms (cache miss)
142 http fetch GET 200 https://registry.npmjs.org/parse5-htmlparser2-tree-adapter/-/parse5-htmlparser2-tree-adapter-7.0.0.tgz 811ms (cache miss)
143 http fetch GET 200 https://registry.npmjs.org/form-data/-/form-data-4.0.0.tgz 795ms (cache miss)
144 http fetch GET 200 https://registry.npmjs.org/whatwg-mimetype/-/whatwg-mimetype-4.0.0.tgz 863ms (cache miss)
145 http fetch GET 200 https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.9.tgz 844ms (cache miss)
146 http fetch GET 200 https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz 907ms (cache miss)
147 http fetch GET 200 https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz 905ms (cache miss)
148 http fetch GET 200 https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz 956ms (cache miss)
149 http fetch GET 200 https://registry.npmjs.org/ws 744ms (cache miss)
150 silly packumentCache corgi:https://registry.npmjs.org/ws set size:undefined disposed:false
151 http fetch GET 200 https://registry.npmjs.org/encoding-sniffer/-/encoding-sniffer-0.2.0.tgz 1020ms (cache miss)
152 silly packumentCache corgi:https://registry.npmjs.org/puppeteer-core cache-miss
153 http fetch GET 200 https://registry.npmjs.org/htmlparser2/-/htmlparser2-9.1.0.tgz 1121ms (cache miss)
154 http fetch GET 200 https://codeload.github.com/xct007/frieren-scraper/tar.gz/9d4fc99ad7752eceeae6d096856fed3d8a02c03d 1042ms (cache miss)
155 http fetch GET 200 https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz 1357ms (cache miss)
156 http fetch GET 200 https://registry.npmjs.org/puppeteer-core 351ms (cache miss)
157 silly packumentCache corgi:https://registry.npmjs.org/puppeteer-core set size:undefined disposed:false
158 http fetch GET 200 https://registry.npmjs.org/parse5/-/parse5-7.1.2.tgz 1570ms (cache miss)
159 silly packumentCache corgi:https://registry.npmjs.org/puppeteer cache-miss
160 http fetch GET 200 https://registry.npmjs.org/axios/-/axios-1.7.7.tgz 1870ms (cache miss)
161 http fetch GET 200 https://registry.npmjs.org/puppeteer 397ms (cache miss)
162 silly packumentCache corgi:https://registry.npmjs.org/puppeteer set size:undefined disposed:false
163 silly packumentCache corgi:https://registry.npmjs.org/whatsapp-web.js cache-miss
164 http fetch GET 200 https://registry.npmjs.org/cheerio/-/cheerio-1.0.0.tgz 2495ms (cache miss)
165 http fetch GET 200 https://registry.npmjs.org/whatsapp-web.js 768ms (cache miss)
166 silly packumentCache corgi:https://registry.npmjs.org/whatsapp-web.js set size:undefined disposed:false
167 verbose stack Error: git dep preparation failed
167 verbose stack     at promiseSpawn (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
167 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/npm.js:13:10)
167 verbose stack     at /usr/lib/node_modules/npm/node_modules/pacote/lib/git.js:183:14
167 verbose stack     at async withTempDir (/usr/lib/node_modules/npm/node_modules/@npmcli/fs/lib/with-temp-dir.js:21:14)
168 error code 2
169 error git dep preparation failed
170 error command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
171 error > @xct007/frieren-scraper@0.0.2 prepare
171 error > npm run build:all
171 error
171 error
171 error > @xct007/frieren-scraper@0.0.2 build:all
171 error > npm run clean && npm run build:esm && npm run build:cjs && npm run build:types && npm run fix && node scripts/write-package.js
171 error
171 error
171 error > @xct007/frieren-scraper@0.0.2 clean
171 error > rimraf ./dist
171 error
171 error
171 error > @xct007/frieren-scraper@0.0.2 build:esm
171 error > tsc -p tsconfig.esm.json
171 error
171 error node_modules/cheerio/dist/commonjs/index.d.ts(7,1): error TS1383: Only named exports may use 'export type'.
171 error node_modules/cheerio/dist/commonjs/slim.d.ts(9,1): error TS1383: Only named exports may use 'export type'.
172 error npm warn using --force Recommended protections disabled.
172 error npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
172 error npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
172 error npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
172 error npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
172 error npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
172 error npm warn using --force Recommended protections disabled.
172 error npm warn using --force Recommended protections disabled.
172 error npm warn using --force Recommended protections disabled.
172 error npm error code 2
172 error npm error path /root/.npm/_cacache/tmp/git-cloneQ1NEZh
172 error npm error command failed
172 error npm error command sh -c npm run build:all
172 error npm error A complete log of this run can be found in: /root/.npm/_logs/2024-09-26T16_57_33_787Z-debug-0.log
173 silly unfinished npm timer reify 1727369847152
174 silly unfinished npm timer reify:unpack 1727369852321
175 silly unfinished npm timer reifyNode:node_modules/@xct007/frieren-scraper 1727369852324
176 verbose cwd /DATA/Documents/botwaweb
177 verbose os Linux 6.1.0-25-amd64
178 verbose node v20.17.0
179 verbose npm  v10.8.3
180 verbose exit 2
181 verbose code 2
182 error A complete log of this run can be found in: /root/.npm/_logs/2024-09-26T16_57_26_430Z-debug-0.log

**Comment by xct007** [comment]
I’ve made changes to address the npm error `git dep preparation failed`. Details are in this [commit](https://github.com/xct007/frieren-scraper/commit/358c2f8a43798063125c78bc8cdff1b03d802569). Please verify if this resolves the issue.
