### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Dantadev** [xct007/frieren-scraper#6]
Scraper game warewolf bot wa

**Comment by xct007** [comment]
meki

**Comment by Dantadev** [comment]
Ayo buat :v

Pada tanggal Jum, 24 Feb 2023 14:40, FrierenDv ***@***.***>
menulis:

**Comment by xct007** [comment]
Contoh nya gimana

**Comment by Dantadev** [comment]
Gausah itu ngab, bkin scrap Spotify

**Comment by xct007** [comment]
> Gausah itu ngab, bkin scrap Spotify

Spotify punya api sendiri, daripada scrape mending pake api nya Spotify.

**Comment by Dantadev** [comment]
Gppa, di jadiin scrap bisa tuh

**Comment by xct007** [comment]
meki

**Comment by RyHarJr** [comment]
> 

Apa api spotify?
