### ISSUE TITLE
Request #4

### ISSUE THREAD

**Issue by Yuri-Neko** [xct007/frieren-scraper#8]
bikin samehadaku.win 
parameter nya
[ search latest detail ]
sama
bokepsin.wiki
param 
[ search detail latest ]

**Comment by xct007** [comment]
> bikin samehadaku.win parameter nya [ search latest detail ] sama bokepsin.wiki param [ search detail latest ]

boke semua ya

**Comment by Yuri-Neko** [comment]
> > bikin samehadaku.win parameter nya [ search latest detail ] sama bokepsin.wiki param [ search detail latest ]
> 
> boke semua ya

🐤yauda klo gitu Sameadaku aja

**Comment by xct007** [comment]
> > > bikin samehadaku.win parameter nya [ search latest detail ] sama bokepsin.wiki param [ search detail latest ]
> > 
> > 
> > boke semua ya
> 
> 🐤yauda klo gitu Sameadaku aja

mau ngapain si cuk, scrape web anime mulu

**Comment by Yuri-Neko** [comment]
> > > > bikin samehadaku.win parameter nya [ search latest detail ] sama bokepsin.wiki param [ search detail latest ]
> > > 
> > > 
> > > boke semua ya
> > 
> > 
> > 🐤yauda klo gitu Sameadaku aja
> 
> mau ngapain si cuk, scrape web anime mulu

🐤ga tau.. kan anoboy mw di rombak :v nah situs lain selain anoboy yang langsung url download setauku cuma samehasaku

**Comment by xct007** [comment]
wibu wibu, nanti taro list dulu
