### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by RyHarJr** [xct007/frieren-scraper#9]
Jadi Anime :)

**Comment by xct007** [comment]
h5 ?

**Comment by RyHarJr** [comment]
> h5 ?

Ya
------------
h5 tu apa?

**Comment by RyHarJr** [comment]
> h5 ?

Bang kalau engga scrape nih bisa ga?
https://getsnackvideo.com/id
snack video

**Comment by xct007** [comment]
> > h5 ?
> 
> ## Ya
> h5 tu apa?

https://h5.tu.qq.com/web/ai-2d/cartoon/index

yang discrape kebanyakan rest api local. Tapi setau ku gabisa request ke web kalo bukan ip dari indo, bisa si pake proxy.
